---
- name: modify tcp profiles
  hosts: all
  connection: local
  gather_facts: False

  vars_prompt:
    - name: "ansible_user"
      prompt: "username" 
      private: False
    - name: "ansible_password"
      prompt: "password" 
      private: True }

  vars:
    provider:
      password: "{{ ansible_password }}"  
      server: "{{ inventory_hostname }}"
      user: "{{ ansible_user }}"
      validate_certs: False
      server_port: 443 

  tasks:
    # Begin Change
    # Webster
    - name: modify tcp profile in n2a
      bigip_profile_tcp:
        provider: "{{ provider }}"
        state: present
        name: "{{ item }}"
        idle_timeout: 1800
      loop:
        - tcpclientpf-alb-hrrs-wlcore-inscompliance-svc-clt-n2a-wdc
        - tcpclientpf-alb-hrrs-wlcore-inscompliance-svc-pyx-n2a-wdc
      when: (inventory_hostname == 'us6645ny-ppcore-ltm-n2a.paychex.com')
      delegate_to: localhost
      tags: 
        - change

    - name: modify tcp profile in n
      bigip_profile_tcp:
        provider: "{{ provider }}"
        state: present
        name: "{{ item }}"
        idle_timeout: 1800
      loop:
        - tcpclientpf-alb-hrrs-wlcore-inscompliance-svc-clt-n0-wdc
        - tcpclientpf-alb-hrrs-wlcore-inscompliance-svc-clt-n1-wdc
        - tcpclientpf-alb-hrrs-wlcore-inscompliance-svc-pyx-n0-wdc
        - tcpclientpf-alb-hrrs-wlcore-inscompliance-svc-pyx-n1-wdc
      when: (inventory_hostname == 'us6645ny-ppcore-ltm-n.paychex.com')
      delegate_to: localhost
      tags: 
        - change

    - name: modify tcp profile in perf
      bigip_profile_tcp:
        provider: "{{ provider }}"
        state: present
        name: "{{ item }}"
        idle_timeout: 1800
      loop:
        - tcpclientpf-alb-hrrs-wlcore-inscompliance-svc-clt-perf-wdc
        - tcpclientpf-alb-hrrs-wlcore-inscompliance-svc-pyx-perf-wdc
      when: (inventory_hostname == 'us6645ny-ppcore-ltm-perf.paychex.com')
      delegate_to: localhost
      tags:
        - change

    # Henrietta
    - name: modify tcp profile in n2a
      bigip_profile_tcp:
        provider: "{{ provider }}"
        state: present
        name: "{{ item }}"
        idle_timeout: 1800
      loop:
        - tcpclientpf-alb-hrrs-wlcore-inscompliance-svc-clt-n2a-hdc
        - tcpclientpf-alb-hrrs-wlcore-inscompliance-svc-pyx-n2a-hdc
      when: (inventory_hostname == 'us6647ny-ppcore-ltm-n2a.paychex.com')
      delegate_to: localhost
      tags: 
        - change

    - name: modify tcp profile in n
      bigip_profile_tcp:
        provider: "{{ provider }}"
        state: present
        name: "{{ item }}"
        idle_timeout: 1800
      loop:
        - tcpclientpf-alb-hrrs-wlcore-inscompliance-svc-clt-n0-hdc
        - tcpclientpf-alb-hrrs-wlcore-inscompliance-svc-clt-n1-hdc
        - tcpclientpf-alb-hrrs-wlcore-inscompliance-svc-pyx-n0-hdc
        - tcpclientpf-alb-hrrs-wlcore-inscompliance-svc-pyx-n1-hdc
      when: (inventory_hostname == 'us6647ny-ppcore-ltm-n.paychex.com')
      delegate_to: localhost
      tags: 
        - change

    - name: modify tcp profile in perf
      bigip_profile_tcp:
        provider: "{{ provider }}"
        state: present
        name: "{{ item }}"
        idle_timeout: 1800
      loop:
        - tcpclientpf-alb-hrrs-wlcore-inscompliance-svc-clt-perf-hdc
        - tcpclientpf-alb-hrrs-wlcore-inscompliance-svc-pyx-perf-hdc
      when: (inventory_hostname == 'us6647ny-ppcore-ltm-perf.paychex.com')
      delegate_to: localhost
      tags:
        - change

    # Rollback
    # Webster
    - name: modify tcp profile in n2a
      bigip_profile_tcp:
        provider: "{{ provider }}"
        state: present
        name: "{{ item }}"
        idle_timeout: 300
      loop:
        - tcpclientpf-alb-hrrs-wlcore-inscompliance-svc-clt-n2a-wdc
        - tcpclientpf-alb-hrrs-wlcore-inscompliance-svc-pyx-n2a-wdc
      when: (inventory_hostname == 'us6645ny-ppcore-ltm-n2a.paychex.com')
      delegate_to: localhost
      tags: 
        - rollback

    - name: modify tcp profile in n
      bigip_profile_tcp:
        provider: "{{ provider }}"
        state: present
        name: "{{ item }}"
        idle_timeout: 300
      loop:
        - tcpclientpf-alb-hrrs-wlcore-inscompliance-svc-clt-n0-wdc
        - tcpclientpf-alb-hrrs-wlcore-inscompliance-svc-clt-n1-wdc
        - tcpclientpf-alb-hrrs-wlcore-inscompliance-svc-pyx-n0-wdc
        - tcpclientpf-alb-hrrs-wlcore-inscompliance-svc-pyx-n1-wdc
      when: (inventory_hostname == 'us6645ny-ppcore-ltm-n.paychex.com')
      delegate_to: localhost
      tags: 
        - rollback

    - name: modify tcp profile in perf
      bigip_profile_tcp:
        provider: "{{ provider }}"
        state: present
        name: "{{ item }}"
        idle_timeout: 300
      loop:
        - tcpclientpf-alb-hrrs-wlcore-inscompliance-svc-clt-perf-wdc
        - tcpclientpf-alb-hrrs-wlcore-inscompliance-svc-pyx-perf-wdc
      when: (inventory_hostname == 'us6645ny-ppcore-ltm-perf.paychex.com')
      delegate_to: localhost
      tags:
        - rollback

    # Henrietta
    - name: modify tcp profile in n2a
      bigip_profile_tcp:
        provider: "{{ provider }}"
        state: present
        name: "{{ item }}"
        idle_timeout: 300
      loop:
        - tcpclientpf-alb-hrrs-wlcore-inscompliance-svc-clt-n2a-hdc
        - tcpclientpf-alb-hrrs-wlcore-inscompliance-svc-pyx-n2a-hdc
      when: (inventory_hostname == 'us6647ny-ppcore-ltm-n2a.paychex.com')
      delegate_to: localhost
      tags: 
        - rollback

    - name: modify tcp profile in n
      bigip_profile_tcp:
        provider: "{{ provider }}"
        state: present
        name: "{{ item }}"
        idle_timeout: 300
      loop:
        - tcpclientpf-alb-hrrs-wlcore-inscompliance-svc-clt-n0-hdc
        - tcpclientpf-alb-hrrs-wlcore-inscompliance-svc-clt-n1-hdc
        - tcpclientpf-alb-hrrs-wlcore-inscompliance-svc-pyx-n0-hdc
        - tcpclientpf-alb-hrrs-wlcore-inscompliance-svc-pyx-n1-hdc
      when: (inventory_hostname == 'us6647ny-ppcore-ltm-n.paychex.com')
      delegate_to: localhost
      tags: 
        - rollback

    - name: modify tcp profile in perf
      bigip_profile_tcp:
        provider: "{{ provider }}"
        state: present
        name: "{{ item }}"
        idle_timeout: 300
      loop:
        - tcpclientpf-alb-hrrs-wlcore-inscompliance-svc-clt-perf-hdc
        - tcpclientpf-alb-hrrs-wlcore-inscompliance-svc-pyx-perf-hdc
      when: (inventory_hostname == 'us6647ny-ppcore-ltm-perf.paychex.com')
      delegate_to: localhost
      tags:
        - rollback
