---
- name: Create F5 Endpoint(s)
  hosts: all
  connection: local
  gather_facts: False

  vars_prompt:
    - name: ansible_user
      prompt: 'Username'
      private: False
    - name: ansible_password
      prompt: 'Password'
      private: True

  vars:
    provider:
      password: '{{ ansible_password }}'
      server: '{{ inventory_hostname }}'
      user: '{{ ansible_user }}'
      validate_certs: False
      server_port: 443

  tasks:
    # Begin Change
    - name: Create Pool(s)
      bigip_pool:
        provider: '{{ provider }}'
        state: present
        name: '{{ item.pool }}'
        lb_method: '{{ item.method }}'
        monitors:
          - tcp
        slow_ramp_time: 120
      loop:
        - {pool: pool-chat-internal, method: least-connections-member}
      delegate_to: localhost
      when: ('ltm1-site-a' in inventory_hostname|upper)
      tags: [change]

    - name: Add Pool Member(s) to Pool
      bigip_pool_member:
        provider: '{{ provider }}'
        state: present
        pool: '{{ item.pool }}'
        address: '{{ item.ip }}'
        name: '{{ item.name }}'
        port: '{{ item.port }}'
      loop:
        - {pool: pool-chat-internal, ip: '10.30.8.25:446', name: ucchat1 port: 446}
        - {pool: pool-chat-internal, ip: '10.30.8.26:446', name: ucchat2 port: 446}
      delegate_to: localhost
      when: ('ltm1-site-a' in inventory_hostname|upper)
      tags: [change]

    - name: Create Virtual Server(s)
      bigip_virtual_server:
        provider: '{{ provider }}'
        state: present
        destination: '{{ item.vip }}'
        enabled_vlans: all
        ip_protocol: tcp
        default_persistence_profile: ssl
        name: '{{ item.server }}'
        type: standard
        profiles:
          - {name: clientsslpf, context: client-side}
          - {name: 'serverssl_no_expire_check', context: server-side}
          - HTTP-X-Forwarded-For
        pool: '{{ item.pool }}'
        port: '{{ item.service_port }}'
        snat: automap
      loop:
        - {server: vs-chat-internal, vip: '10.2.219.251', service_port: 446, pool: pool-chat-internal, node_port: 446}
      delegate_to: localhost
      when: ('ltm1-site-a' in inventory_hostname|upper)
      tags: [change]
